### ISSUE TITLE
spiped: Error looking up  [0.0.0.0]: Name does not resolve

### ISSUE THREAD

**Issue by Kami-no** [Tarsnap/spiped#188]
Trying to launch spiped in k8s and have a problem:
```
spiped: WARNING: Applying workaround for Docker signal-handling bug
spiped: Error looking up  [0.0.0.0]: Name does not resolve
spiped: Error resolving socket address:  [0.0.0.0]:6379
```

Dockerfile
```
FROM alpine:3.8

RUN addgroup -S spiped \
&&  adduser -S -G spiped spiped

RUN apk add --no-cache libssl1.0

ENV SPIPED_DOWNLOAD_URL https://www.tarsnap.com/spiped/spiped-1.6.0.tgz
ENV SPIPED_DOWNLOAD_SHA256 e6f7f8f912172c3ad55638af8346ae7c4ecaa92aed6d3fb60f2bda4359cba1e4

RUN set -x \
&&  apk add --no-cache --virtual .build-deps \
        curl \
        gcc \
        make \
        musl-dev \
        openssl-dev \
        tar \
&&  curl -fsSL "$SPIPED_DOWNLOAD_URL" -o spiped.tar.gz \
&&  echo "$SPIPED_DOWNLOAD_SHA256 *spiped.tar.gz" |sha256sum -c - \
&&  mkdir -p /usr/local/src/spiped \
&&  tar xzf "spiped.tar.gz" -C /usr/local/src/spiped --strip-components=1 \
&&  rm "spiped.tar.gz" \
&&  CC=gcc make -C /usr/local/src/spiped \
&&  make -C /usr/local/src/spiped install \
&&  rm -rf /usr/local/src/spiped \
&&  apk del .build-deps

WORKDIR /opt

USER spiped:spiped

ENTRYPOINT ["/usr/local/bin/spiped"]
```
k8s
```
    spec:
      containers:
        - name: spiped
          image: 1.2.3.4/spiped:latest
          ports:
            - name: tcp
              containerPort: 6379
          args:
            - '-F'
            - '-e'
            - '-s [0.0.0.0]:6379'
            - '-t [1.2.3.4]:16379'
            - '-k /opt/spiped.key'
            - '-o 30
```
